config/routes.rb
Rails.application.routes.draw do
  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  resources :users, only: %i[index show create edit update destroy]
  resources :spendings, only: %i[index show new create edit update destroy]
  resources :share_spendings, only: %i[index]
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spending.rb
class Spending < ApplicationRecord
  enum category: { traveling: 0, clothing: 1, taxi: 2, cafes: 3, shops: 4, other: 5 }
  belongs_to :user
  validates :category, presence: true
  validates :description, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spendings
  has_secure_password
  validates :password_digest, presence: true
  validates :name, presence: true
  validates :email, presence: true, format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
                                              message: 'Invalid e-mail! Please provide a valid e-mail address'}, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authorization
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    private

    def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
    end

    def user_signed_in?
      current_user.present?
    end

    def require_authentication
      return if user_signed_in?
      redirect_to root_path
    end

    def sign_in(user)
      session[:user_id] = user.id
    end

    def sign_out
      session.delete :user_id
    end

    helper_method :current_user, :user_signed_in?
  end
end

app/controllers/concerns/authorization.rb
module Authorization
  extend ActiveSupport::Concern

  included do
    include Pundit::Authorization

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    private

    def user_not_authorized
      redirect_back(fallback_location: login_path)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:email]

    if user&.authenticate(params[:password])
      sign_in user
      flash[:notice] = "Logged in successfully."
      redirect_to spendings_path
    else
      flash.now[:alert] = "There was something wrong with your login details."
      redirect_to login_path
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/share_spendings_controller.rb
class ShareSpendingsController < ApplicationController
  def index
    @user = User.find(params.required(:user_id))
    @spendings = @user.spendings
    @total = @spendings.sum(:amount)
  end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :require_authentication

  def index
    @spendings = current_user.spendings
    @spendings = @spendings.where(category: params[:category]) if params[:category].present?
    @spendings = @spendings.where(amount: params[:amount_from]..) if params[:amount_from].present?
    @spendings = @spendings.where('amount <= ?', params[:amount_to].to_f) if params[:amount_to].present?
    @spendings = @spendings.where("description like ?", "%#{params[:description]}%") if params[:description].present?
    @total = @spendings.sum(:amount)
    @share_link = share_spendings_url(user_id: current_user.id)
  end

  def new
    @spending = Spending.new
    @categories = Spending.categories.keys
  end

  def create
    @spending = Spending.new spending_params.merge(user_id: current_user.id)

    if @spending.save
      flash[:success] = "Spending created!"
      redirect_to spendings_path
    else
      render new_spending_path
    end
  end

  def update
    spending = Spending.find(params[:id])

    if spending.update spending_params
      redirect_to spendings_path
    else
      render spendings_id_path
    end
  end

  def show
    @spending = Spending.find(params[:id])
    @categories = Spending.categories.keys
  end

  def edit
    @spending = Spending.find(params[:id])
    @categories = Spending.categories.keys
  end

  def destroy
    spending = Spending.find(params[:id])
    spending.destroy
    redirect_to spendings_path
  end

  private

  def spending_params
    params.require(:spending).permit(:category, :description, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
  end

  def create
    @user = User.new user_params

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "User created."
      redirect_to spendings_path
    else
      render :new
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_tab(title, url, options = {})
    current_page = options.delete :current_page

    css_class = current_page == title ? 'text-secondary' : 'text-white'

    options[:class] = if options[:class]
      options[:class] + ' ' + css_class
    else
      css_class
    end

    link_to title, url, options
  end

  def currently_at(current_page = '')
    render partial: 'shared/menu', locals: {current_page: current_page}
  end

  def full_title(page_title = "")
    base_title ="Wallet"
    if page_title.present?
      "#{page_title} | #{base_title}"
    else
      base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= full_title(yield(:page_title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield :main_menu %>
    <main class="container mt-3", style="margin: 20px auto">
      <% flash.each do |k, v| %>
        <%= tag.div v, class: "alert alert-#{k}", role: 'alert' %>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/share_spendings/index.html.erb
<% provide :page_title, 'Spendings' %>
<% currently_at 'Spendings' %>
<h1 class="mb-4">Spendings for user <%= @user.name %>:</h1>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="col-md-2">Category</th>
        <th scope="col" class="col-md-2">Amount</th>
        <th scope="col" class="col-md-6">Description</th>
      </tr>
    </thead>
    <tbody>
      <% @spendings.each do |spending| %>
        <tr >
          <td><%= spending.category %></td>
          <td><%= spending.amount %></td>
          <td style="word-break: break-all"><%= spending.description %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h1>Total: <%= @total %></h1>
</div>

app/views/shared/_menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <% if policy(Spending).index? %>
            <li><%= nav_tab 'My spendings', spendings_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li>
              <%= nav_tab current_user.name, '#',
                class: 'nav-link px-2', current_page: current_page %>
              <li>
                <%= button_to 'Log out', logout_path,
                    class: 'btn btn-secondary', method: :delete %>
              </li>
            </li>
          <% else %>
            <li><%= nav_tab 'Log In', login_path,
              class: 'nav-link px-2', current_page: current_page %></li>
            <li><%= nav_tab 'Sign Up', signup_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/shared/menu.html.erb
<%= provide :main_menu do %>
  <header class="p-3 bg-dark text-white">
    <div class="container">
      <nav class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><%= nav_tab 'Home', root_path, class: 'nav-link px-2', current_page: current_page %></li>
          <li><%= nav_tab 'Authors', authors_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% if policy(Genre).index? %>
            <li><%= nav_tab 'Genres', genres_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
          <% if policy(Admin).index? %>
            <li><%= nav_tab 'Admins', admins_path, class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
        <ul class="nav col-12 col-lg-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="dropdown">
              <%= nav_tab current_user.name, '#',
                class: 'nav-link px-2 dropdown-toggle',
                data: {"bs-toggle": 'dropdown'}, current_page: current_page %>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'Log out', session_path,
                    class: 'dropdown-item', data: {method: :delete} %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= nav_tab 'Log In', new_session_path,
              class: 'nav-link px-2', current_page: current_page %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </header>
<% end %>

app/views/spendings/_form.html.erb
<div class="container-sm">
  <%= form_with model: @spending do |f| %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :category %>
      </div>
      <div class="col-sm-10">
        <%= f.select :category, @categories, {}, class: 'form-select form-select-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :amount %>
      </div>
      <div class="col-sm-10">
        <%= f.number_field :amount, class: 'form-control form-control-lg', step: 0.01 %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, class: 'form-control form-control-lg' %>
      </div>
    </div>
    <%= f.submit "#{@spending&.id ? "Update" : "Create"} Spending ", class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/spendings/edit.html.erb
<% currently_at 'Spending' %>
<h1 class="mb-4">Edit spending #<%= @spending.id %></h1>
<%= render 'form' %>

app/views/spendings/index.html.erb
<% if policy(@spendings).index? %>
  <% provide :page_title, 'Spendings' %>
  <% currently_at 'Spendings' %>
  <div class='d-flex justify-content-between'>
    <h1 class="mb-4">My Spendings:</h1>
    <%= button_to "+ Add spending", new_spending_path, :id => 'open-contacts-dialog-btn',
      class: 'btn btn-primary btn-lg', :method => :get %>
  </div>
  <%= form_tag(spendings_path, method: :get, class: 'mb-5') do %>
    <div class='d-flex mb-3'>
      <div class="form-group p-1">
        <label class="mb-1">Category:</label>
        <%= select_tag :category, options_for_select({ all: nil }.merge(Spending::categories), params[:category]), class: "form-select" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Amount From:</label>
        <%= number_field_tag :amount_from, params[:amount_from], step: 0.01, class: "form-control" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Amount To:</label>
        <%= number_field_tag :amount_to, params[:amount_to], step: 0.01, class: "form-control" %>
      </div>
      <div class="form-group p-1">
        <label class="mb-1">Description contains:</label>
        <%= text_field_tag :description, params[:description], class: "form-control" %>
      </div>
    </div>
    <%= submit_tag 'Apply Filters' , name: nil, class: 'btn btn-secondary' %>
  <% end %>
  <div class="mb-5">
    <label class="mb-1">Share my spendings:</label>
    <input class="form-control" type="text" value=<%=@share_link%> readonly></input>
</div>
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col" class="col-md-2">Category</th>
        <th scope="col" class="col-md-2">Amount</th>
        <th scope="col" class="col-md-6">Description</th>
        <th scope="col" class="col-md-2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @spendings.each do |spending| %>
        <tr>
          <td><%= spending.category %></td>
          <td><%= spending.amount %></td>
          <td style="word-break: break-all"><%= spending.description %></td>
          <td class="d-flex justify-content-around">
            <%= link_to "Show", spending_path(spending), class: 'btn btn-secondary btn-sm', method: :get %>
            <%= link_to "Edit", edit_spending_path(spending), class: 'btn btn-secondary btn-sm', method: :get %>
            <%= button_to "Destroy", spending_path(spending), class: 'btn btn-danger btn-sm', method: :delete %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <h1>Total: <%= @total %></h1>
</div>
<% end %>

app/views/spendings/new.html.erb
<% currently_at 'Spending' %>
<h1 class="mb-4">Create new spending</h1>
<%= render 'form' %>

app/views/spendings/show.html.erb
<% currently_at 'Spending' %>
<h1 class="mb-4">Spending #<%= @spending.id %></h1>
<div class="container-sm">
  <%= form_with model: @spending do |f| %>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :category %>
      </div>
      <div class="col-sm-10">
        <%= f.select :category, @categories, {}, disabled: true, class: 'form-select form-select-lg' %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :amount %>
      </div>
      <div class="col-sm-10">
        <%= f.number_field :amount, readonly: true, class: 'form-control form-control-lg', step: 0.01 %>
      </div>
    </div>
    <div class="mb-3 row">
      <div class="col-sm-2 col-form-label">
        <%= f.label :description %>
      </div>
      <div class="col-sm-10">
        <%= f.text_area :description, readonly: true, class: 'form-control form-control-lg' %>
      </div>
    </div>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :email %>
    </div>
    <div class="col-sm-10">
      <%= f.email_field :email, placeholder: 'E-mail', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :name %>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name, placeholder: 'Name', required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password, required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <div class="mb-3 row">
    <div class="col-sm-2 col-form-label">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-sm-10">
      <%= f.password_field :password_confirmation, required: true, class: 'form-control form-control-lg' %>
    </div>
  </div>
  <%= f.submit "Register ", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<% provide :page_title, 'Registration' %>
<% currently_at 'Sign Up' %>
<h1 class="mb-4 text-center">Registration</h1>
<%= render 'form' %>

app/views/welcome/index.html.erb
<% provide :page_title, 'Welcome' %>
<% currently_at 'Welcome' %>
<div class="text-center mt-5">
  <h1 class="display-1  mb-5">Welcome to <span class="text-primary">Wallet App</span></h1>
  <h2 >
    Please, <%= link_to "Log In", login_path, class: 'btn btn-primary btn-lg', :method => :get %>
    or <%= link_to "Sign Up", signup_path, class: 'btn btn-primary btn-lg', :method => :get %>
    to proceed.
  </h2>
</div>